define:
  &colors [
    aqua,
    black,
    blue,
    brown,
    green,
    grey,
    orange,
    pink,
    purple,
    red,
    white,
    yellow,
  ]

vest:
  types: [jacket, vest, coat]
  colors: *colors
top:
  types: ["tank top", "shirt", "sweater", "blouse"]
  colors: *colors
bottom:
  types: ["shorts", "pants", "legging", "skirt", "jeans"]
  colors: *colors
skirt:
  length: ["mini", "medium", "long"]

dress:
  china: [
    "china:0.1",
    ""
  ]
  length: [
    "short",
    "medium",
    "long"
  ]
  sleeves: [
    "sleeveless:0.25",
    "off-shoulder:0.25",
    ":0.5"
  ]
  colors: *colors

uniform:
  colors: *colors
  types: [military, school, gym, police, employee, naval]
