dark_nipples: [
  "dark nipples:0.2",
  ":0.8"
]

nipple_piercing: [
  "nipple piercing:0.5",
  ":0.95"
]

puffy_nipples: [
  "puffy nipples:0.1",
  ":0.9"
]

huge_nipples: [
  "huge nipples:0.05",
  ":0.95"
]

fat_mons: [
  "fat mons:0.15",
  ":0.85"
]

pussy_piercing: [
  "pussy piercing:0.05",
  ":0.95"
]

pubic_hair: [
  "excessive pubic hair:0.5",
  "pubic hair:0.5",
  ":1"
]